server:
  servlet:
    # JSON防止中文乱码
    encoding:
      force-response: true
    # 为所有Controller添加统一访问前缀
    # context-path: /api
spring:
  # 多环境配置
  profiles:
    # 从Maven配置中读取选择的环境变量（开发环境：dev/生产环境：prod）
    active: '@environment@'
  # Spring MVC 配置
  mvc:
    # SpringBoot 2.6以上版本修改了路径匹配规则，但是Swagger3还不支持
    # 这里换回之前的，不然启动会直接报错
    pathmatch:
      matching-strategy: ant_path_matcher
    # 静态资源配置
    static-path-pattern: /static/**
